version: "3"
# 我这个 docker compose 由几个服务组成
services:
  mysql8:
    image: mysql:5.7.44
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
#      - 初始化脚本
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
#      - 外部访问用 13316
      - 3306:3306
